#import "@preview/wordometer:0.1.4": word-count, total-words

#set text(size: 11pt, font: "Times New Roman")
#show: word-count

As a successful second-language learner of English, I have long been fascinated by what enables some learners to attain native-like proficiency while others plateau despite equal effort. I am eager to pursue graduate studies in linguistics to further investigate how individual differences in second language acquisition relate to ultimate attainment. Understanding the cognitive factors underlying L2 learning variability is my ultimate research goal.

My academic background has provided me with a strong foundation in linguistic theory and research methodology. Besides completing an undergraduate degree in linguistics and computer science, I have conducted linguistic fieldwork under Professor Suzi Lima, leading elicitation sessions on the syntax and semantics of Tshiluba and Kirundi. Additionally, as a member of the Toronto Language and Cognition Lab under Professor Myrto Grigoroglou, I have worked on a cross-linguistic study on event conceptualization and description, gaining experience in experimental design, data processing, and collaborative research. These experiences have honed my ability to critically engage with academic literature and research methodology.

Building on this foundation, I initiated an independent research project supervised by Professor Jeffrey Steele, examining the roles of language aptitude and working memory in predicting phonetic production gains among beginner French learners. I designed a longitudinal study that assesses both segmental and prosodic phonology, conducted two rounds of piloting, and reported preliminary findings in a research paper. Our study refines methods for operationalizing pronunciation proficiency by analyzing plosive VOT, phrasal stress, fluency, and perceived global accent, ensuring a comprehensive approach to measuring phonetic learning.

Despite the theoretical and practical significance of understanding individual differences in language learning, existing research often examines only surface-level phenomena like fluency and vocabulary, overlooking deeper phonological and syntactic knowledge. Conversely, studies focusing on phonological acquisition tend to treat L2 learners as a homogeneous group, ignoring intra-group variability. My exploratory project is among the first to explicitly investigate the links between language aptitude and the acquisition of specific phonetic and phonological features, making it an original contribution to the field.

During my graduate studies at uOttawa, I aim to continue this line of research to investigate how individual differences predict L2 learners’ success in acquiring native-like phonetic and phonological patterns. I also plan to explore perception-production links in L2 learners to determine whether aptitude-related pronunciation effects are in fact modulated through perception. I am fascinated by Professor Suzy Ahn's research, specifically around building the NNA corpus. With her expertise in articulatory and acoustic phonetics, and her work with advanced acoustic analysis tools, I will be able to examine L2 pronunciation at a much more fine-grained level. I will also benefit greatly from working with Professor Juana M. Liceras, whose extensive experience in bilingualism and acquisition research will help me refine my methodology and potentially translate my results into pedagogical insights, which is another prospect I am very excited about.

With my experience, knowledge, and dedication to the field, I am confident that uOttawa’s graduate program will provide the solid foundation I need to advance my career as a linguistics researcher.
